import fs from "fs";
import path from "path";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

/**
 * Home page — renders the AI-generated resume from data/generated/resume.md.
 *
 * This is a server component that reads the markdown file at build time.
 * The resume is generated by the pipeline: npm run pipeline
 * To regenerate: edit scripts/generate-resume.ts and run npm run generate
 */
export default function Home() {
  const resumePath = path.join(process.cwd(), "data", "generated", "resume.md");
  let resumeMarkdown: string;

  try {
    resumeMarkdown = fs.readFileSync(resumePath, "utf-8");
  } catch {
    return (
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-bold mb-4">paulprae.com</h1>
        <p className="text-slate-600">
          Resume not yet generated. Run{" "}
          <code className="bg-slate-100 px-2 py-0.5 rounded text-sm">
            npm run pipeline
          </code>{" "}
          after adding your LinkedIn data to{" "}
          <code className="bg-slate-100 px-2 py-0.5 rounded text-sm">
            data/sources/linkedin/
          </code>
          .
        </p>
      </main>
    );
  }

  // Strip HTML comments (generation metadata) from display
  const cleanMarkdown = resumeMarkdown.replace(/<!--[\s\S]*?-->\n*/g, "");

  return (
    <main className="max-w-3xl mx-auto px-6 py-12 print:py-4 print:px-0 print:max-w-none">
      <article className="resume-prose prose prose-slate max-w-none">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {cleanMarkdown}
        </ReactMarkdown>
      </article>
    </main>
  );
}
