/**
 * build-prompts.ts — Pre-build system prompts at pipeline time.
 *
 * Generates lib/generated/system-prompts.ts with all system prompt strings
 * as TypeScript constants. This eliminates runtime file I/O from the hot path
 * and produces byte-identical strings on every request, maximizing Anthropic
 * prompt cache hit rates.
 *
 * Run: npm run build:prompts
 * Called automatically by: npm run pipeline, npm run pipeline:content
 */

import fs from "fs";
import path from "path";
import { buildSystemPrompt } from "../lib/agent/context";
import {
  loadCareerData,
  getCurrentRole,
  getCurrentEmployer,
  getCurrentEmployerUrl,
  formatCurrentRoleSentence,
  formatCurrentRoleHero,
} from "../lib/career-data";

const MODES = ["chat", "tools", "resume-generator"] as const;
type PromptMode = (typeof MODES)[number];

const OUTPUT_DIR = path.join(process.cwd(), "lib", "generated");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "system-prompts.ts");
const CURRENT_ROLE_FILE = path.join(OUTPUT_DIR, "current-role.ts");

function run() {
  const prompts: Record<string, string> = {};
  const missing: PromptMode[] = [];

  for (const mode of MODES) {
    const prompt = buildSystemPrompt(mode);
    if (!prompt) {
      missing.push(mode);
    } else {
      prompts[mode] = prompt;
    }
  }

  if (missing.length > 0) {
    console.error(
      `[build-prompts] Failed to build prompts for: ${missing.join(", ")}. ` +
        `Ensure the pipeline has been run (npm run ingest) before building prompts.`,
    );
    process.exit(1);
  }

  const entries = Object.entries(prompts)
    .map(([mode, text]) => `  ${JSON.stringify(mode)}: ${JSON.stringify(text)},`)
    .join("\n");

  const output = `// AUTO-GENERATED by scripts/build-prompts.ts — do not edit directly.
// Regenerate: npm run build:prompts (or npm run pipeline)
// These are pre-built system prompt strings committed alongside career-data.json.
// Pre-building eliminates runtime file I/O and ensures byte-identical strings
// for consistent Anthropic prompt cache hit rates.

export const SYSTEM_PROMPTS = {
${entries}
} as const;

export type PromptMode = keyof typeof SYSTEM_PROMPTS;
`;

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`[build-prompts] Written ${Object.keys(prompts).length} prompts to ${OUTPUT_FILE}`);
  for (const [mode, text] of Object.entries(prompts)) {
    console.log(`  ${mode}: ${text.length.toLocaleString()} chars`);
  }

  // ── Emit lib/generated/current-role.ts ──────────────────────────────────
  // Client-safe constants derived from career-data.json so that constants.ts,
  // QuickActions, and other client components can reference the current role
  // without importing fs. Regenerated on every build:prompts run.
  const careerData = loadCareerData();
  if (careerData) {
    const role = getCurrentRole(careerData);
    const employer = getCurrentEmployer(careerData);

    // Load companies.json for employer URL lookup (SSOT for company websites)
    const companiesPath = path.join(
      process.cwd(),
      "data",
      "sources",
      "knowledge",
      "career",
      "companies.json",
    );
    let companies: Array<Record<string, unknown>> = [];
    try {
      const raw = JSON.parse(fs.readFileSync(companiesPath, "utf-8"));
      const entries = raw.data ?? raw;
      companies = Array.isArray(entries) ? entries : [entries];
    } catch {
      /* companies.json missing — URL will be empty */
    }

    const currentRoleOutput = `// AUTO-GENERATED by scripts/build-prompts.ts — do not edit directly.
// Regenerate: npm run build:prompts (or npm run pipeline)
// Client-safe constants derived from career-data.json so that
// lib/constants.ts and client components can reference the current
// employer without importing server-only modules.

export const CURRENT_ROLE_TITLE = ${JSON.stringify(role?.title ?? "")};
export const CURRENT_EMPLOYER = ${JSON.stringify(employer)};
export const CURRENT_EMPLOYER_URL = ${JSON.stringify(getCurrentEmployerUrl(employer, companies))};
export const CURRENT_ROLE_SENTENCE = ${JSON.stringify(formatCurrentRoleSentence(careerData))};
export const CURRENT_ROLE_HERO = ${JSON.stringify(formatCurrentRoleHero(careerData))};
`;
    fs.writeFileSync(CURRENT_ROLE_FILE, currentRoleOutput, "utf-8");
    console.log(
      `[build-prompts] Written current-role constants to ${CURRENT_ROLE_FILE}` +
        ` (employer: ${getCurrentEmployer(careerData) || "(none)"})`,
    );
  }
}

run();
