import fs from "fs";
import path from "path";
import type { Metadata } from "next";
import type { Components } from "react-markdown";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { stripHtmlComments, stripHeaderBlock } from "../../lib/markdown";
import { PATHS } from "../../lib/config";
import { loadCareerData } from "../../lib/career-data";
import { slugify } from "../../lib/ui-utils";
import { DownloadIcon } from "../components/Icons";
import SiteNav from "../components/SiteNav";
import {
  SITE_NAME,
  SITE_SUBTITLE,
  SITE_DOMAIN,
  SITE_URL,
  SITE_OG_DESCRIPTION,
  GITHUB_URL,
  CONTACT_LINK_CLASS,
  RESUME_DOWNLOAD_PATHS,
  RESUME_PUBLIC_FILE_BASE,
} from "../../lib/constants";
import BackToTop from "./components/BackToTop";
import SectionNav from "./components/SectionNav";

// ─── Metadata ────────────────────────────────────────────────────────────────

const resumeTitle = `${SITE_NAME} — Resume | ${SITE_SUBTITLE}`;

export const metadata: Metadata = {
  title: resumeTitle,
  description: SITE_OG_DESCRIPTION,
  alternates: {
    canonical: `${SITE_URL}/resume`,
  },
  openGraph: {
    title: resumeTitle,
    description: SITE_OG_DESCRIPTION,
    type: "website",
    url: `${SITE_URL}/resume`,
    siteName: SITE_NAME,
    locale: "en_US",
    images: [
      {
        url: `${SITE_URL}/og-image.png`,
        width: 1200,
        height: 630,
        alt: `${SITE_NAME} — ${SITE_SUBTITLE}`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: resumeTitle,
    description: SITE_OG_DESCRIPTION,
    images: [`${SITE_URL}/og-image.png`],
  },
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Returns human-readable file size (e.g. "63 KB") or null if file doesn't exist. */
function getFileSize(filePath: string): string | null {
  try {
    const bytes = fs.statSync(filePath).size;
    return `${Math.round(bytes / 1024)} KB`;
  } catch {
    return null;
  }
}

/** Extract H2 sections from markdown for the section navigation bar. */
function extractSections(markdown: string): { id: string; label: string }[] {
  const matches = markdown.matchAll(/^## (.+)$/gm);
  return [...matches].map((m) => {
    const label = m[1].trim();
    return { id: slugify(label), label };
  });
}

// ─── Page Component ──────────────────────────────────────────────────────────

/**
 * Resume page — renders the AI-generated resume from the pipeline output.
 *
 * This is a server component that reads the markdown file at build time.
 * The resume filename is derived from career data (e.g. "Paul-Prae-Resume.md").
 * The resume is generated by the pipeline: npm run pipeline
 * To regenerate: edit scripts/generate-resume.ts and run npm run generate
 */
export default function ResumePage() {
  const careerData = loadCareerData();
  const resumePath = PATHS.resumeOutput;
  let resumeMarkdown: string;

  try {
    resumeMarkdown = fs.readFileSync(resumePath, "utf-8");
  } catch {
    return (
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-bold mb-4">{SITE_DOMAIN}</h1>
        <p className="text-slate-600 dark:text-slate-400">
          Resume not yet generated. Run{" "}
          <code className="bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-sm">
            npm run pipeline
          </code>{" "}
          after adding your LinkedIn data to{" "}
          <code className="bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-sm">
            data/sources/linkedin/
          </code>
          .
        </p>
      </main>
    );
  }

  if (!careerData) {
    return (
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-2xl font-bold mb-4">{SITE_DOMAIN}</h1>
        <p className="text-slate-600 dark:text-slate-400">
          Career data not found. Run{" "}
          <code className="bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-sm">
            npm run ingest
          </code>{" "}
          to generate{" "}
          <code className="bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-sm">
            career-data.json
          </code>{" "}
          from your LinkedIn data.
        </p>
      </main>
    );
  }

  // Strip HTML comments (generation metadata) from display
  const cleanMarkdown = stripHtmlComments(resumeMarkdown);

  const profile = careerData.profile;
  const pdfPath = RESUME_DOWNLOAD_PATHS.pdf;
  const docxPath = RESUME_DOWNLOAD_PATHS.docx;
  const mdPath = RESUME_DOWNLOAD_PATHS.md;

  // Read file sizes at build time for download button labels
  const publicDir = path.join(process.cwd(), "public");
  const pdfSize = getFileSize(path.join(publicDir, `${RESUME_PUBLIC_FILE_BASE}.pdf`));
  const docxSize = getFileSize(path.join(publicDir, `${RESUME_PUBLIC_FILE_BASE}.docx`));
  const mdSize = getFileSize(path.join(publicDir, `${RESUME_PUBLIC_FILE_BASE}.md`));

  // Strip the header block (H1 + contact line + HR) — already shown in the
  // sticky header, so we don't render it again in the body.
  const bodyMarkdown = stripHeaderBlock(cleanMarkdown);

  // Extract section headings for the navigation bar
  const sections = extractSections(bodyMarkdown);

  // ─── Markdown component overrides ──────────────────────────────────────────

  const markdownComponents: Components = {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    h2: ({ children, node, ...props }) => {
      const id = slugify(String(children ?? ""));
      return (
        <h2 id={id} {...props}>
          {children}
        </h2>
      );
    },

    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    a: ({ href, children, node, ...props }) => {
      const isExternal = href?.startsWith("http");
      return (
        <a
          href={href}
          {...(isExternal ? { target: "_blank", rel: "noopener noreferrer" } : {})}
          {...props}
        >
          {children}
        </a>
      );
    },
  };

  return (
    <>
      {/* Skip navigation — keyboard-only, hidden on touch devices (see globals.css .skip-nav) */}
      <a href="#resume-content" className="skip-nav">
        Skip to resume content
      </a>

      <SiteNav>
        {/* Row 2: Contact + Downloads (resume page only) */}
        <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-2">
          {profile.email && (
            <a
              href={`mailto:${profile.email}`}
              aria-label="Send email to Paul Prae"
              className={CONTACT_LINK_CLASS}
            >
              Email
            </a>
          )}
          {profile.linkedin && (
            <a
              href={profile.linkedin}
              target="_blank"
              rel="me noopener noreferrer"
              aria-label="View Paul Prae on LinkedIn"
              className={CONTACT_LINK_CLASS}
            >
              LinkedIn
            </a>
          )}
          {profile.github && (
            <a
              href={profile.github}
              target="_blank"
              rel="me noopener noreferrer"
              aria-label="View Paul Prae on GitHub"
              className={CONTACT_LINK_CLASS}
            >
              GitHub
            </a>
          )}
          {/* Separator between contact and download groups */}
          <span
            aria-hidden="true"
            className="select-none px-1.5 text-xs text-slate-300 dark:text-slate-600"
          >
            ·
          </span>
          <a
            href={pdfPath}
            download
            aria-label="Download resume as PDF"
            className={CONTACT_LINK_CLASS}
          >
            <DownloadIcon className="h-3.5 w-3.5" />
            PDF{pdfSize && <span className="opacity-60">({pdfSize})</span>}
          </a>
          <a
            href={docxPath}
            download
            aria-label="Download resume as DOCX"
            className={CONTACT_LINK_CLASS}
          >
            <DownloadIcon className="h-3.5 w-3.5" />
            DOCX{docxSize && <span className="opacity-60">({docxSize})</span>}
          </a>
          <a
            href={mdPath}
            download
            aria-label="Download resume as Markdown"
            className={CONTACT_LINK_CLASS}
          >
            <DownloadIcon className="h-3.5 w-3.5" />
            MD{mdSize && <span className="opacity-60">({mdSize})</span>}
          </a>
        </div>
      </SiteNav>

      <SectionNav sections={sections} />

      <main
        id="resume-content"
        tabIndex={-1}
        className="max-w-3xl mx-auto px-6 py-8 print:py-4 print:px-0 print:max-w-none focus:outline-none"
      >
        <h1 className="sr-only">{profile.name} — Resume</h1>
        <article className="resume-prose prose prose-slate max-w-none">
          <ReactMarkdown remarkPlugins={[remarkGfm]} components={markdownComponents}>
            {bodyMarkdown}
          </ReactMarkdown>
        </article>
        {/* Bottom spacer ensures the last resume sections (Projects, Publications)
            can scroll to the top of the viewport when clicked in the section nav.
            Without this, the page bottoms out and the heading stays mid-viewport.
            Hidden on print to avoid wasting paper. */}
        <div className="no-print h-[50vh]" aria-hidden="true" />
      </main>

      <footer className="no-print max-w-3xl mx-auto px-6 pb-8 pt-4 border-t border-slate-200 dark:border-slate-800">
        <div className="flex flex-col sm:flex-row sm:justify-between gap-1 text-xs text-slate-600 dark:text-slate-400">
          <p>
            &copy; {new Date().getFullYear()} {profile.name} &mdash; AI-generated resume &mdash;{" "}
            <a
              href={GITHUB_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="text-slate-600 underline hover:text-slate-800 focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:rounded focus-visible:outline-none dark:text-slate-400 dark:hover:text-slate-200"
            >
              view pipeline on GitHub
            </a>
          </p>
          <p>Built with Next.js, Claude AI, and Tailwind CSS</p>
        </div>
      </footer>

      <BackToTop />
    </>
  );
}
